### ISSUE TITLE
Using Easywave2MQTT outside homeassistant

### ISSUE THREAD

**Issue by ced2git** [marcselis/Easywave2MQTT#7]
Hello, 

iv' bought an Eldat USB receiver and installed Easywave2Mqtt as a container. I'm not using HomeAssistant but Jeedom instead. I've added Easywave in a MQTT app of Jeedom. 

Whenever i press a Niko 4 button, i will see the topic update so it's all fine. Now, i would like to pilot from Jeedom towards Easywave. I've tried to issue an MQTT message with the topic easywave2mqtt/1b4d8f/action and the payload : button_A_press. I was expecting this message to toggle the light linked with button A but it's not working. 

Maybe you could help me ? 

Thanks for your support.

**Comment by marcselis** [comment]
I'm sorry, but that is not technically possible.  The Eldat stick can listen to all EasyWave messages that are being transmitted on all channels, but is only able to send out messages for channel `000000` to `00003f` (for the 64 channel version) or `00007f` (for the 128 channel version).

To work around this technical limit, Easywave2MQTT works with a list of devices, which are defined in the [config file](https://github.com/marcselis/Easywave2MQTT/blob/main/addon/Easywave2MQTT/app/appsettings.json). This configuration allows Easywave2MQTT to know about and instruct the physical world around it.  You'll need to adapt that file to your situation. 

The following example means that there is a physical EasyWave switch with 2 buttons, named `Terrace Switch` that is located in the `Kitchen` area, which is sending Easywave messages on channel `229ad6`.

``` json
{
  "Id": "229ad6",
  "Type": "Transmitter",
  "Name": "Terrace Switch",
  "Area": "Kitchen",
  "Buttons": [ "A", "B" ]
}
```

Easywave2MQTT will the listen for messages from that switch, and try to figure out the intent of the user when pressing that switch.  Based on the detected intent, it will send out a message to MQTT.  The message `easywave2mqtt/229ad6/action` with payload `button_A_press` simply means that it detected that button A was pressed on that switch.  Other intents are `double press`, `triple press`, `hold` and `release`.

You can also declare lights in the config file.  The following example means that there is a light called `Terrace` which is located in the `Outside` area that is paired to button `A` of the switch that sends on channel `229ad6` (the one we defined above).  This means that whenever button `A` is pressed on that switch, the light will automatically turn on and also implies that button `B` will turn it off.
You also see a second subscription, and that is where the Eldat stick comes into play.  The terrace light is also paired with with (virtual) button `A` of channel `000070`, which is a channel that the Eldat stick can send, hence the `CanSend: true`.

``` json
{
  "Id": "terrace",
  "Type": "Light",
  "Name": "Terrace",
  "Area": "Outside",
  "Subscriptions": [
    {
      "Address": "229ad6",
      "KeyCode": "A"
    },
    {
      "Address": "000070",
      "KeyCode": "A",
      "CanSend": "true"
    }
  ]
}
```

When this configuration is entered in Easywave2MQTT it will do its best to reflect the real-life situation to MQTT.  That means that when it sees a button `A` press on channel `229ad6`, it knows that terrace light will have turned on, and will also send out a `easywave2mqtt/terrace/state` message with payload `on`.

Now for the part you are probably most interested in: in order to turn the light on or off using MTT, you can send a `mqtt2easywave/terras/set` message with payload `on` or `off`.  Easywave2MQTT will see that message and look for a subscription on that device with `CanSend: true´ and if it finds one, instruct the Eldat stick to send out the corresponding button message on the corresponding channel, which in its turn will turn the light on or off.

At the moment your lights will probably will not be paired with a channel from the Eldat stick yet.  For that you'll need to put the light in pairing mode (your manual can tell you how to do that), and once it is in pairing mode, you can send a message through MQTT to turn the light on, which will in its turn cause Easywave2MQTT to send out the `CanSend: true` button message through the Eldat stick. Once your light receives that message it will indicate that the pairing was successful, after which you can put the light back in normal operating mode.  From then on you'll be able to operate the light through MQTT.

Good luck!

**Comment by ced2git** [comment]
Hello Marc,
Thanks a lot for the extensive information. I will try this tomorrow. One last question
I do have 3 transmitters ( 2x4 buttons and 1x2 buttons). I assume that i need to define all of them including in the light definition where I need to list all button linked to one light including the Elat 
Regards Cedric 
Envoyé d un smartphone... Le 3 oct. 2023 à 20:12

**Comment by marcselis** [comment]
Yes, you'll need to add the 3 transmitters and for each of them list the buttons they have.
For the lights you only need to specify the transmitter channel and button that was pressed during pairing (typically `A` or `C`) and the Eldat Stick's channel and button you want to use for pairing.
